import XCTest
@testable import TwentyFourDefend

/// Validates that the Swift PhishingClassifier produces identical features
/// and scores to the Python training pipeline (ml/features.py).
/// Ground truth generated by ml/features.py and stored in python_feature_ground_truth.json.
final class PhishingClassifierTests: XCTestCase {

    struct GroundTruth: Codable {
        let features: [String: Double]
        let feature_vector: [Double]
        let score: Double
    }

    var groundTruth: [String: GroundTruth] = [:]

    override func setUp() {
        super.setUp()
        // Load Python ground truth
        guard let url = Bundle(for: type(of: self)).url(forResource: "python_feature_ground_truth", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let decoded = try? JSONDecoder().decode([String: GroundTruth].self, from: data) else {
            XCTFail("Failed to load python_feature_ground_truth.json")
            return
        }
        groundTruth = decoded
    }

    /// Test that Swift scores match Python scores within tolerance.
    func testScoresMatchPython() {
        for (domain, truth) in groundTruth {
            let prediction = PhishingClassifier.predict(domain)
            let diff = abs(prediction.score - truth.score)
            XCTAssertLessThan(diff, 0.01,
                "Score mismatch for '\(domain)': Swift=\(prediction.score), Python=\(truth.score), diff=\(diff)")
        }
    }

    /// Test known phishing domains are flagged.
    func testPhishingDomainsDetected() {
        let phishing = [
            "brou-seguro.com",
            "actualizacion-brou-2026.xyz",
            "verificar-itau.top",
            "br0u.com.uy",
            "login.santander-verificacion.click",
            "homebanking-brou.net",
            "itau-verificar-cuenta.xyz",
            "santander-bloqueo-urgente.top",
        ]

        for domain in phishing {
            let pred = PhishingClassifier.predict(domain)
            XCTAssertTrue(pred.isPhishing,
                "Expected phishing for '\(domain)' but got score=\(pred.score)")
        }
    }

    /// Test legitimate domains are not flagged.
    func testLegitimateDomainsAllowed() {
        let legit = [
            "google.com",
            "facebook.com",
            "elobservador.com.uy",
            "cafe-jardin.com.uy",
            "tienda-norte.com",
        ]

        for domain in legit {
            let pred = PhishingClassifier.predict(domain)
            XCTAssertFalse(pred.isPhishing,
                "False positive for '\(domain)': score=\(pred.score)")
        }
    }

    /// Test high-risk threshold.
    func testHighRiskThreshold() {
        // Brand + phishing word + risky TLD should be high risk
        let pred = PhishingClassifier.predict("actualizacion-brou-2026.xyz")
        XCTAssertTrue(pred.isHighRisk, "Expected high risk, got score=\(pred.score)")

        // Clean domain should not be high risk
        let clean = PhishingClassifier.predict("google.com")
        XCTAssertFalse(clean.isHighRisk, "False high risk for google.com: score=\(clean.score)")
    }
}
